### ISSUE TITLE
Implement the use of Fractions module to work with rational numbers in a simple format.

### ISSUE THREAD

**Issue by Wellington475** [vmesel/GeoMath#18]
More  information: https://docs.python.org/3/library/fractions.html

**Comment by vmesel** [comment]
Do you really think it's necessary to implement it? I really think it would be nice to use when we are using periodic decimals or giant decimals. What about u?

**Comment by Wellington475** [comment]
Some numbers that GeoMath generates are in extensive decimals. So it is more visually presentable, for those using.

**Comment by vmesel** [comment]
We should give this a try. We need to defines what is the maximum size to display as float and which is the minimum size for fractions

**Comment by Wellington475** [comment]
Yes, perfect!

**Comment by vmesel** [comment]
@Wellington475 are you available to start working on this part?

**Comment by Wellington475** [comment]
@vmesel, these two weeks will not be available. However, as soon as I finished my personal tasks, will contribute more often.

**Comment by vmesel** [comment]
@Wellington475 no problema, tnx buddy! I will try to get this fixed this week! Whenever you want, u contribute!

**Comment by vmesel** [comment]
Already implemented in general.py
