### ISSUE TITLE
Documentation needs to be done!

### ISSUE THREAD

**Issue by vmesel** [vmesel/GeoMath#5]

**Comment by vmesel** [comment]
@Wellington475 @rg3915 galera, como vcs acham que deveria ser feita uma doc de uma lib de matemática?

**Comment by vmesel** [comment]
Galera, já sei que a gente vai ter que fazer essa documentação toda em HTML e CSS, alguma ideia para usar como template ou algo do gênero?

**Comment by vmesel** [comment]
Usar o sphinx e arrumar o readme

**Comment by rg3915** [comment]
@vmesel use o sphinx em MarkDown.

**Comment by vmesel** [comment]
Biblioteca sendo feita! Valeu pelo auxílio @rg3915 !
